# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: mA2Ai 
email: ma2pulation.ai@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/weblog" # the subpath of your site, e.g. /blog
url: "https://ma2ai.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: ma2ai
github_username: ma2ai

# Build settings

include: ["_pages"]
# permalink: /:title/

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives

# remote_theme: wowthemesnet/mediumish-theme-jekyll@81ab472
remote_theme: wowthemesnet/mundana-theme-jekyll@cf3ec79

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: pvmilk
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
 
authors:
    pvmilk:
      name:           Milk Phongtharin
      site:           https://pvmilk.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hello, I am Milk!"
      # bio:            "Hello, I am Milk, the founder of mA2Ai!"
      email:          pvmilk@gmail.com
      twitter:        https://twitter.com/milLII3yway
